# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/sc3d/image.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.math import tensor_pb2 as standard__cyborg_dot_proto_dot_math_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/sc3d/image.proto',
  package='standard_cyborg.proto.sc3d',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n&standard_cyborg/proto/sc3d/image.proto\x12\x1astandard_cyborg.proto.sc3d\x1a\'standard_cyborg/proto/math/tensor.proto\"\xf9\x01\n\x05Image\x12\r\n\x05\x66rame\x18\x01 \x01(\t\x12\x32\n\x06pixels\x18\x02 \x01(\x0b\x32\".standard_cyborg.proto.math.Tensor\x12\x41\n\x0b\x63olor_space\x18\n \x01(\x0e\x32,.standard_cyborg.proto.sc3d.Image.ColorSpace\"j\n\nColorSpace\x12\x17\n\x13\x43OLOR_SPACE_UNKNOWN\x10\x00\x12\x16\n\x12\x43OLOR_SPACE_LINEAR\x10\x01\x12\x14\n\x10\x43OLOR_SPACE_SRGB\x10\x02\x12\x15\n\x11\x43OLOR_SPACE_DEPTH\x10\x64\x62\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_math_dot_tensor__pb2.DESCRIPTOR,])



_IMAGE_COLORSPACE = _descriptor.EnumDescriptor(
  name='ColorSpace',
  full_name='standard_cyborg.proto.sc3d.Image.ColorSpace',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COLOR_SPACE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR_SPACE_LINEAR', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR_SPACE_SRGB', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COLOR_SPACE_DEPTH', index=3, number=100,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=255,
  serialized_end=361,
)
_sym_db.RegisterEnumDescriptor(_IMAGE_COLORSPACE)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='standard_cyborg.proto.sc3d.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='standard_cyborg.proto.sc3d.Image.frame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixels', full_name='standard_cyborg.proto.sc3d.Image.pixels', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color_space', full_name='standard_cyborg.proto.sc3d.Image.color_space', index=2,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMAGE_COLORSPACE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=361,
)

_IMAGE.fields_by_name['pixels'].message_type = standard__cyborg_dot_proto_dot_math_dot_tensor__pb2._TENSOR
_IMAGE.fields_by_name['color_space'].enum_type = _IMAGE_COLORSPACE
_IMAGE_COLORSPACE.containing_type = _IMAGE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'standard_cyborg.proto.sc3d.image_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.Image)
  })
_sym_db.RegisterMessage(Image)


# @@protoc_insertion_point(module_scope)
