# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/sc3d/imu.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from standard_cyborg.proto.math import core_pb2 as standard__cyborg_dot_proto_dot_math_dot_core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/sc3d/imu.proto',
  package='standard_cyborg.proto.sc3d',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n$standard_cyborg/proto/sc3d/imu.proto\x12\x1astandard_cyborg.proto.sc3d\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%standard_cyborg/proto/math/core.proto\"\x85\x03\n\x11\x43MDeviceMotionMsg\x12\r\n\x05\x66rame\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x08rotation\x18\x03 \x01(\x0b\x32 .standard_cyborg.proto.math.Vec3\x12\x31\n\x07gravity\x18\x04 \x01(\x0b\x32 .standard_cyborg.proto.math.Vec3\x12\x36\n\x0c\x61\x63\x63\x65leration\x18\x05 \x01(\x0b\x32 .standard_cyborg.proto.math.Vec3\x12\x1f\n\x17magnetic_field_accuracy\x18\x06 \x01(\x01\x12\x38\n\x0emagnetic_field\x18\x07 \x01(\x0b\x32 .standard_cyborg.proto.math.Vec3\x12\x38\n\x08\x61ttitude\x18\x08 \x01(\x0b\x32&.standard_cyborg.proto.math.Quaternionb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_math_dot_core__pb2.DESCRIPTOR,])




_CMDEVICEMOTIONMSG = _descriptor.Descriptor(
  name='CMDeviceMotionMsg',
  full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg.frame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg.rotation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gravity', full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg.gravity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg.acceleration', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='magnetic_field_accuracy', full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg.magnetic_field_accuracy', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='magnetic_field', full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg.magnetic_field', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attitude', full_name='standard_cyborg.proto.sc3d.CMDeviceMotionMsg.attitude', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=530,
)

_CMDEVICEMOTIONMSG.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CMDEVICEMOTIONMSG.fields_by_name['rotation'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
_CMDEVICEMOTIONMSG.fields_by_name['gravity'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
_CMDEVICEMOTIONMSG.fields_by_name['acceleration'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
_CMDEVICEMOTIONMSG.fields_by_name['magnetic_field'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
_CMDEVICEMOTIONMSG.fields_by_name['attitude'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._QUATERNION
DESCRIPTOR.message_types_by_name['CMDeviceMotionMsg'] = _CMDEVICEMOTIONMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CMDeviceMotionMsg = _reflection.GeneratedProtocolMessageType('CMDeviceMotionMsg', (_message.Message,), {
  'DESCRIPTOR' : _CMDEVICEMOTIONMSG,
  '__module__' : 'standard_cyborg.proto.sc3d.imu_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.CMDeviceMotionMsg)
  })
_sym_db.RegisterMessage(CMDeviceMotionMsg)


# @@protoc_insertion_point(module_scope)
