# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/sc3d/label_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.math import core_pb2 as standard__cyborg_dot_proto_dot_math_dot_core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/sc3d/label_2d.proto',
  package='standard_cyborg.proto.sc3d',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n)standard_cyborg/proto/sc3d/label_2d.proto\x12\x1astandard_cyborg.proto.sc3d\x1a%standard_cyborg/proto/math/core.proto\"S\n\x07Label2D\x12\x34\n\nposition2D\x18\x01 \x01(\x0b\x32 .standard_cyborg.proto.math.Vec2\x12\x12\n\nisOccluded\x18\x02 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_math_dot_core__pb2.DESCRIPTOR,])




_LABEL2D = _descriptor.Descriptor(
  name='Label2D',
  full_name='standard_cyborg.proto.sc3d.Label2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position2D', full_name='standard_cyborg.proto.sc3d.Label2D.position2D', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isOccluded', full_name='standard_cyborg.proto.sc3d.Label2D.isOccluded', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=195,
)

_LABEL2D.fields_by_name['position2D'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC2
DESCRIPTOR.message_types_by_name['Label2D'] = _LABEL2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Label2D = _reflection.GeneratedProtocolMessageType('Label2D', (_message.Message,), {
  'DESCRIPTOR' : _LABEL2D,
  '__module__' : 'standard_cyborg.proto.sc3d.label_2d_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.Label2D)
  })
_sym_db.RegisterMessage(Label2D)


# @@protoc_insertion_point(module_scope)
