# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/sc3d/label_3d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.math import core_pb2 as standard__cyborg_dot_proto_dot_math_dot_core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/sc3d/label_3d.proto',
  package='standard_cyborg.proto.sc3d',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n)standard_cyborg/proto/sc3d/label_3d.proto\x12\x1astandard_cyborg.proto.sc3d\x1a%standard_cyborg/proto/math/core.proto\"?\n\x07Label3D\x12\x34\n\nposition3D\x18\x01 \x01(\x0b\x32 .standard_cyborg.proto.math.Vec3b\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_math_dot_core__pb2.DESCRIPTOR,])




_LABEL3D = _descriptor.Descriptor(
  name='Label3D',
  full_name='standard_cyborg.proto.sc3d.Label3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position3D', full_name='standard_cyborg.proto.sc3d.Label3D.position3D', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=175,
)

_LABEL3D.fields_by_name['position3D'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
DESCRIPTOR.message_types_by_name['Label3D'] = _LABEL3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Label3D = _reflection.GeneratedProtocolMessageType('Label3D', (_message.Message,), {
  'DESCRIPTOR' : _LABEL3D,
  '__module__' : 'standard_cyborg.proto.sc3d.label_3d_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.Label3D)
  })
_sym_db.RegisterMessage(Label3D)


# @@protoc_insertion_point(module_scope)
