# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/sc3d/landmark.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.math import core_pb2 as standard__cyborg_dot_proto_dot_math_dot_core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/sc3d/landmark.proto',
  package='standard_cyborg.proto.sc3d',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n)standard_cyborg/proto/sc3d/landmark.proto\x12\x1astandard_cyborg.proto.sc3d\x1a%standard_cyborg/proto/math/core.proto\"[\n\x08Landmark\x12\r\n\x05\x66rame\x18\x01 \x01(\t\x12\x32\n\x08position\x18\x02 \x01(\x0b\x32 .standard_cyborg.proto.math.Vec3\x12\x0c\n\x04name\x18\x03 \x01(\tb\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_math_dot_core__pb2.DESCRIPTOR,])




_LANDMARK = _descriptor.Descriptor(
  name='Landmark',
  full_name='standard_cyborg.proto.sc3d.Landmark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='standard_cyborg.proto.sc3d.Landmark.frame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='standard_cyborg.proto.sc3d.Landmark.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='standard_cyborg.proto.sc3d.Landmark.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=203,
)

_LANDMARK.fields_by_name['position'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
DESCRIPTOR.message_types_by_name['Landmark'] = _LANDMARK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Landmark = _reflection.GeneratedProtocolMessageType('Landmark', (_message.Message,), {
  'DESCRIPTOR' : _LANDMARK,
  '__module__' : 'standard_cyborg.proto.sc3d.landmark_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.Landmark)
  })
_sym_db.RegisterMessage(Landmark)


# @@protoc_insertion_point(module_scope)
