# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/sc3d/perspective_camera.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.math import core_pb2 as standard__cyborg_dot_proto_dot_math_dot_core__pb2
from standard_cyborg.proto.math import transform_pb2 as standard__cyborg_dot_proto_dot_math_dot_transform__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/sc3d/perspective_camera.proto',
  package='standard_cyborg.proto.sc3d',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n3standard_cyborg/proto/sc3d/perspective_camera.proto\x12\x1astandard_cyborg.proto.sc3d\x1a%standard_cyborg/proto/math/core.proto\x1a*standard_cyborg/proto/math/transform.proto\"\xf7\x02\n\rPinholeCamera\x12\r\n\x05\x66rame\x18\x01 \x01(\t\x12\x36\n\x0c\x66ocal_length\x18\n \x01(\x0b\x32 .standard_cyborg.proto.math.Vec2\x12\x39\n\x0fprincipal_point\x18\x0b \x01(\x0b\x32 .standard_cyborg.proto.math.Vec2\x12\x13\n\x0bsensor_skew\x18\x0c \x01(\x02\x12\x14\n\x0cimage_height\x18\r \x01(\x03\x12\x13\n\x0bimage_width\x18\x0e \x01(\x03\x12?\n\x10sensor_transform\x18\x14 \x01(\x0b\x32%.standard_cyborg.proto.math.Transform\x12\x1c\n\x14pixel_pitch_width_mm\x18\x1e \x01(\x01\x12\x1d\n\x15pixel_pitch_height_mm\x18\x1f \x01(\x01\x12&\n\x1eradial_distortion_coefficients\x18  \x03(\x02\x62\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_math_dot_core__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_math_dot_transform__pb2.DESCRIPTOR,])




_PINHOLECAMERA = _descriptor.Descriptor(
  name='PinholeCamera',
  full_name='standard_cyborg.proto.sc3d.PinholeCamera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='standard_cyborg.proto.sc3d.PinholeCamera.frame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='focal_length', full_name='standard_cyborg.proto.sc3d.PinholeCamera.focal_length', index=1,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='principal_point', full_name='standard_cyborg.proto.sc3d.PinholeCamera.principal_point', index=2,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_skew', full_name='standard_cyborg.proto.sc3d.PinholeCamera.sensor_skew', index=3,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_height', full_name='standard_cyborg.proto.sc3d.PinholeCamera.image_height', index=4,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_width', full_name='standard_cyborg.proto.sc3d.PinholeCamera.image_width', index=5,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_transform', full_name='standard_cyborg.proto.sc3d.PinholeCamera.sensor_transform', index=6,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_pitch_width_mm', full_name='standard_cyborg.proto.sc3d.PinholeCamera.pixel_pitch_width_mm', index=7,
      number=30, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pixel_pitch_height_mm', full_name='standard_cyborg.proto.sc3d.PinholeCamera.pixel_pitch_height_mm', index=8,
      number=31, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radial_distortion_coefficients', full_name='standard_cyborg.proto.sc3d.PinholeCamera.radial_distortion_coefficients', index=9,
      number=32, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=542,
)

_PINHOLECAMERA.fields_by_name['focal_length'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC2
_PINHOLECAMERA.fields_by_name['principal_point'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC2
_PINHOLECAMERA.fields_by_name['sensor_transform'].message_type = standard__cyborg_dot_proto_dot_math_dot_transform__pb2._TRANSFORM
DESCRIPTOR.message_types_by_name['PinholeCamera'] = _PINHOLECAMERA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PinholeCamera = _reflection.GeneratedProtocolMessageType('PinholeCamera', (_message.Message,), {
  'DESCRIPTOR' : _PINHOLECAMERA,
  '__module__' : 'standard_cyborg.proto.sc3d.perspective_camera_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.PinholeCamera)
  })
_sym_db.RegisterMessage(PinholeCamera)


# @@protoc_insertion_point(module_scope)
