# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/sc3d/polyline.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.math import tensor_pb2 as standard__cyborg_dot_proto_dot_math_dot_tensor__pb2
from standard_cyborg.proto.math import core_pb2 as standard__cyborg_dot_proto_dot_math_dot_core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/sc3d/polyline.proto',
  package='standard_cyborg.proto.sc3d',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n)standard_cyborg/proto/sc3d/polyline.proto\x12\x1astandard_cyborg.proto.sc3d\x1a\'standard_cyborg/proto/math/tensor.proto\x1a%standard_cyborg/proto/math/core.proto\"?\n\x08Polyline\x12\x33\n\tpositions\x18\x01 \x03(\x0b\x32 .standard_cyborg.proto.math.Vec3b\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_math_dot_tensor__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_math_dot_core__pb2.DESCRIPTOR,])




_POLYLINE = _descriptor.Descriptor(
  name='Polyline',
  full_name='standard_cyborg.proto.sc3d.Polyline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='standard_cyborg.proto.sc3d.Polyline.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=216,
)

_POLYLINE.fields_by_name['positions'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
DESCRIPTOR.message_types_by_name['Polyline'] = _POLYLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Polyline = _reflection.GeneratedProtocolMessageType('Polyline', (_message.Message,), {
  'DESCRIPTOR' : _POLYLINE,
  '__module__' : 'standard_cyborg.proto.sc3d.polyline_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.Polyline)
  })
_sym_db.RegisterMessage(Polyline)


# @@protoc_insertion_point(module_scope)
