# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/sc3d/video.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.math import tensor_pb2 as standard__cyborg_dot_proto_dot_math_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/sc3d/video.proto',
  package='standard_cyborg.proto.sc3d',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n&standard_cyborg/proto/sc3d/video.proto\x12\x1astandard_cyborg.proto.sc3d\x1a\'standard_cyborg/proto/math/tensor.proto\"Q\n\x05Video\x12\x15\n\rfileExtension\x18\x01 \x01(\t\x12\x31\n\x05\x62ytes\x18\x02 \x01(\x0b\x32\".standard_cyborg.proto.math.Tensorb\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_math_dot_tensor__pb2.DESCRIPTOR,])




_VIDEO = _descriptor.Descriptor(
  name='Video',
  full_name='standard_cyborg.proto.sc3d.Video',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileExtension', full_name='standard_cyborg.proto.sc3d.Video.fileExtension', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='standard_cyborg.proto.sc3d.Video.bytes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=192,
)

_VIDEO.fields_by_name['bytes'].message_type = standard__cyborg_dot_proto_dot_math_dot_tensor__pb2._TENSOR
DESCRIPTOR.message_types_by_name['Video'] = _VIDEO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Video = _reflection.GeneratedProtocolMessageType('Video', (_message.Message,), {
  'DESCRIPTOR' : _VIDEO,
  '__module__' : 'standard_cyborg.proto.sc3d.video_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.sc3d.Video)
  })
_sym_db.RegisterMessage(Video)


# @@protoc_insertion_point(module_scope)
