# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/scene_graph/scene_graph.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.scene_graph import scene_graph_node_pb2 as standard__cyborg_dot_proto_dot_scene__graph_dot_scene__graph__node__pb2
from standard_cyborg.proto.math import transform_pb2 as standard__cyborg_dot_proto_dot_math_dot_transform__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/scene_graph/scene_graph.proto',
  package='standard_cyborg.proto.scene_graph',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n3standard_cyborg/proto/scene_graph/scene_graph.proto\x12!standard_cyborg.proto.scene_graph\x1a\x38standard_cyborg/proto/scene_graph/scene_graph_node.proto\x1a*standard_cyborg/proto/math/transform.proto\"\x89\x01\n\nSceneGraph\x12@\n\x05nodes\x18\x01 \x03(\x0b\x32\x31.standard_cyborg.proto.scene_graph.SceneGraphNode\x12\x39\n\ntransforms\x18\x02 \x03(\x0b\x32%.standard_cyborg.proto.math.Transformb\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_scene__graph_dot_scene__graph__node__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_math_dot_transform__pb2.DESCRIPTOR,])




_SCENEGRAPH = _descriptor.Descriptor(
  name='SceneGraph',
  full_name='standard_cyborg.proto.scene_graph.SceneGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='standard_cyborg.proto.scene_graph.SceneGraph.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transforms', full_name='standard_cyborg.proto.scene_graph.SceneGraph.transforms', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=330,
)

_SCENEGRAPH.fields_by_name['nodes'].message_type = standard__cyborg_dot_proto_dot_scene__graph_dot_scene__graph__node__pb2._SCENEGRAPHNODE
_SCENEGRAPH.fields_by_name['transforms'].message_type = standard__cyborg_dot_proto_dot_math_dot_transform__pb2._TRANSFORM
DESCRIPTOR.message_types_by_name['SceneGraph'] = _SCENEGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SceneGraph = _reflection.GeneratedProtocolMessageType('SceneGraph', (_message.Message,), {
  'DESCRIPTOR' : _SCENEGRAPH,
  '__module__' : 'standard_cyborg.proto.scene_graph.scene_graph_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.scene_graph.SceneGraph)
  })
_sym_db.RegisterMessage(SceneGraph)


# @@protoc_insertion_point(module_scope)
