# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_cyborg/proto/scene_graph/scene_graph_node.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from standard_cyborg.proto.sc3d import polyline_pb2 as standard__cyborg_dot_proto_dot_sc3d_dot_polyline__pb2
from standard_cyborg.proto.sc3d import image_pb2 as standard__cyborg_dot_proto_dot_sc3d_dot_image__pb2
from standard_cyborg.proto.sc3d import perspective_camera_pb2 as standard__cyborg_dot_proto_dot_sc3d_dot_perspective__camera__pb2
from standard_cyborg.proto.sc3d import point_cloud_pb2 as standard__cyborg_dot_proto_dot_sc3d_dot_point__cloud__pb2
from standard_cyborg.proto.sc3d import triangle_mesh_pb2 as standard__cyborg_dot_proto_dot_sc3d_dot_triangle__mesh__pb2
from standard_cyborg.proto.sc3d import plane_pb2 as standard__cyborg_dot_proto_dot_sc3d_dot_plane__pb2
from standard_cyborg.proto.sc3d import landmark_pb2 as standard__cyborg_dot_proto_dot_sc3d_dot_landmark__pb2
from standard_cyborg.proto.math import core_pb2 as standard__cyborg_dot_proto_dot_math_dot_core__pb2
from standard_cyborg.proto.math import transform_pb2 as standard__cyborg_dot_proto_dot_math_dot_transform__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_cyborg/proto/scene_graph/scene_graph_node.proto',
  package='standard_cyborg.proto.scene_graph',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n8standard_cyborg/proto/scene_graph/scene_graph_node.proto\x12!standard_cyborg.proto.scene_graph\x1a)standard_cyborg/proto/sc3d/polyline.proto\x1a&standard_cyborg/proto/sc3d/image.proto\x1a\x33standard_cyborg/proto/sc3d/perspective_camera.proto\x1a,standard_cyborg/proto/sc3d/point_cloud.proto\x1a.standard_cyborg/proto/sc3d/triangle_mesh.proto\x1a&standard_cyborg/proto/sc3d/plane.proto\x1a)standard_cyborg/proto/sc3d/landmark.proto\x1a%standard_cyborg/proto/math/core.proto\x1a*standard_cyborg/proto/math/transform.proto\"\xdd\x05\n\x0eSceneGraphNode\x12\x10\n\x08nodeName\x18\x02 \x01(\t\x12\x35\n\x0bobjectColor\x18\x03 \x01(\x0b\x32 .standard_cyborg.proto.math.Vec3\x12\x15\n\rmaterialModel\x18\x04 \x01(\x05\x12\x10\n\x08\x63hildren\x18\x06 \x03(\x05\x12\x38\n\ttransform\x18\x05 \x01(\x0b\x32%.standard_cyborg.proto.math.Transform\x12\x38\n\x08polyline\x18\x14 \x01(\x0b\x32$.standard_cyborg.proto.sc3d.PolylineH\x00\x12\x32\n\x05image\x18\x15 \x01(\x0b\x32!.standard_cyborg.proto.sc3d.ImageH\x00\x12\x42\n\rpinholeCamera\x18\x16 \x01(\x0b\x32).standard_cyborg.proto.sc3d.PinholeCameraH\x00\x12<\n\npointCloud\x18\x17 \x01(\x0b\x32&.standard_cyborg.proto.sc3d.PointCloudH\x00\x12@\n\x0ctriangleMesh\x18\x18 \x01(\x0b\x32(.standard_cyborg.proto.sc3d.TriangleMeshH\x00\x12\x32\n\x05plane\x18\x19 \x01(\x0b\x32!.standard_cyborg.proto.sc3d.PlaneH\x00\x12\x38\n\x08landmark\x18\x1a \x01(\x0b\x32$.standard_cyborg.proto.sc3d.LandmarkH\x00\x12\x17\n\risGenericNode\x18\x1b \x01(\x08H\x00\x12\x1f\n\x15isCoordinateFrameNode\x18\x1c \x01(\x08H\x00\x12\x39\n\rpointPosition\x18\x1d \x01(\x0b\x32 .standard_cyborg.proto.math.Vec3H\x00\x42\n\n\x08\x63ontentsb\x06proto3'
  ,
  dependencies=[standard__cyborg_dot_proto_dot_sc3d_dot_polyline__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_sc3d_dot_image__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_sc3d_dot_perspective__camera__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_sc3d_dot_point__cloud__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_sc3d_dot_triangle__mesh__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_sc3d_dot_plane__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_sc3d_dot_landmark__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_math_dot_core__pb2.DESCRIPTOR,standard__cyborg_dot_proto_dot_math_dot_transform__pb2.DESCRIPTOR,])




_SCENEGRAPHNODE = _descriptor.Descriptor(
  name='SceneGraphNode',
  full_name='standard_cyborg.proto.scene_graph.SceneGraphNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeName', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.nodeName', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objectColor', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.objectColor', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='materialModel', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.materialModel', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.children', index=3,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transform', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.transform', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='polyline', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.polyline', index=5,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.image', index=6,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pinholeCamera', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.pinholeCamera', index=7,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pointCloud', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.pointCloud', index=8,
      number=23, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='triangleMesh', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.triangleMesh', index=9,
      number=24, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plane', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.plane', index=10,
      number=25, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landmark', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.landmark', index=11,
      number=26, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isGenericNode', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.isGenericNode', index=12,
      number=27, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isCoordinateFrameNode', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.isCoordinateFrameNode', index=13,
      number=28, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pointPosition', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.pointPosition', index=14,
      number=29, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='contents', full_name='standard_cyborg.proto.scene_graph.SceneGraphNode.contents',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=492,
  serialized_end=1225,
)

_SCENEGRAPHNODE.fields_by_name['objectColor'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
_SCENEGRAPHNODE.fields_by_name['transform'].message_type = standard__cyborg_dot_proto_dot_math_dot_transform__pb2._TRANSFORM
_SCENEGRAPHNODE.fields_by_name['polyline'].message_type = standard__cyborg_dot_proto_dot_sc3d_dot_polyline__pb2._POLYLINE
_SCENEGRAPHNODE.fields_by_name['image'].message_type = standard__cyborg_dot_proto_dot_sc3d_dot_image__pb2._IMAGE
_SCENEGRAPHNODE.fields_by_name['pinholeCamera'].message_type = standard__cyborg_dot_proto_dot_sc3d_dot_perspective__camera__pb2._PINHOLECAMERA
_SCENEGRAPHNODE.fields_by_name['pointCloud'].message_type = standard__cyborg_dot_proto_dot_sc3d_dot_point__cloud__pb2._POINTCLOUD
_SCENEGRAPHNODE.fields_by_name['triangleMesh'].message_type = standard__cyborg_dot_proto_dot_sc3d_dot_triangle__mesh__pb2._TRIANGLEMESH
_SCENEGRAPHNODE.fields_by_name['plane'].message_type = standard__cyborg_dot_proto_dot_sc3d_dot_plane__pb2._PLANE
_SCENEGRAPHNODE.fields_by_name['landmark'].message_type = standard__cyborg_dot_proto_dot_sc3d_dot_landmark__pb2._LANDMARK
_SCENEGRAPHNODE.fields_by_name['pointPosition'].message_type = standard__cyborg_dot_proto_dot_math_dot_core__pb2._VEC3
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['polyline'])
_SCENEGRAPHNODE.fields_by_name['polyline'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['image'])
_SCENEGRAPHNODE.fields_by_name['image'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['pinholeCamera'])
_SCENEGRAPHNODE.fields_by_name['pinholeCamera'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['pointCloud'])
_SCENEGRAPHNODE.fields_by_name['pointCloud'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['triangleMesh'])
_SCENEGRAPHNODE.fields_by_name['triangleMesh'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['plane'])
_SCENEGRAPHNODE.fields_by_name['plane'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['landmark'])
_SCENEGRAPHNODE.fields_by_name['landmark'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['isGenericNode'])
_SCENEGRAPHNODE.fields_by_name['isGenericNode'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['isCoordinateFrameNode'])
_SCENEGRAPHNODE.fields_by_name['isCoordinateFrameNode'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
_SCENEGRAPHNODE.oneofs_by_name['contents'].fields.append(
  _SCENEGRAPHNODE.fields_by_name['pointPosition'])
_SCENEGRAPHNODE.fields_by_name['pointPosition'].containing_oneof = _SCENEGRAPHNODE.oneofs_by_name['contents']
DESCRIPTOR.message_types_by_name['SceneGraphNode'] = _SCENEGRAPHNODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SceneGraphNode = _reflection.GeneratedProtocolMessageType('SceneGraphNode', (_message.Message,), {
  'DESCRIPTOR' : _SCENEGRAPHNODE,
  '__module__' : 'standard_cyborg.proto.scene_graph.scene_graph_node_pb2'
  # @@protoc_insertion_point(class_scope:standard_cyborg.proto.scene_graph.SceneGraphNode)
  })
_sym_db.RegisterMessage(SceneGraphNode)


# @@protoc_insertion_point(module_scope)
